# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import enzona_payment
from enzona_payment.models.payload3 import Payload3  # noqa: E501
from enzona_payment.rest import ApiException


class TestPayload3(unittest.TestCase):
    """Payload3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayload3(self):
        """Test Payload3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enzona_payment.models.payload3.Payload3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
