# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import enzona_payment
from enzona_payment.models.payment_summary_info_operations_operation_amount_details import PaymentSummaryInfoOperationsOperationAmountDetails  # noqa: E501
from enzona_payment.rest import ApiException


class TestPaymentSummaryInfoOperationsOperationAmountDetails(unittest.TestCase):
    """PaymentSummaryInfoOperationsOperationAmountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentSummaryInfoOperationsOperationAmountDetails(self):
        """Test PaymentSummaryInfoOperationsOperationAmountDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enzona_payment.models.payment_summary_info_operations_operation_amount_details.PaymentSummaryInfoOperationsOperationAmountDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
