# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class LinksSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rel': 'str',
        'method': 'str',
        'href': 'str'
    }

    attribute_map = {
        'rel': 'rel',
        'method': 'method',
        'href': 'href'
    }

    def __init__(self, rel=None, method=None, href=None):  # noqa: E501
        """LinksSchema - a model defined in Swagger"""  # noqa: E501

        self._rel = None
        self._method = None
        self._href = None
        self.discriminator = None

        if rel is not None:
            self.rel = rel
        if method is not None:
            self.method = method
        if href is not None:
            self.href = href

    @property
    def rel(self):
        """Gets the rel of this LinksSchema.  # noqa: E501


        :return: The rel of this LinksSchema.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this LinksSchema.


        :param rel: The rel of this LinksSchema.  # noqa: E501
        :type: str
        """
        # allowed_values = ["confirm"]  # noqa: E501
        # if rel not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `rel` ({0}), must be one of {1}"  # noqa: E501
        #         .format(rel, allowed_values)
        #     )

        self._rel = rel

    @property
    def method(self):
        """Gets the method of this LinksSchema.  # noqa: E501


        :return: The method of this LinksSchema.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this LinksSchema.


        :param method: The method of this LinksSchema.  # noqa: E501
        :type: str
        """
        # allowed_values = ["REDIRECT"]  # noqa: E501
        # if method not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `method` ({0}), must be one of {1}"  # noqa: E501
        #         .format(method, allowed_values)
        #     )

        self._method = method

    @property
    def href(self):
        """Gets the href of this LinksSchema.  # noqa: E501


        :return: The href of this LinksSchema.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this LinksSchema.


        :param href: The href of this LinksSchema.  # noqa: E501
        :type: str
        """
        # allowed_values = ["https://enzona.xetid.cu/checkout/1940841ec89d4f32aef06c813825920b/login"]  # noqa: E501
        # if href not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `href` ({0}), must be one of {1}"  # noqa: E501
        #         .format(href, allowed_values)
        #     )

        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinksSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinksSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
