# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from enzona_payment.models.full_operations_operation_amount import FullOperationsOperationAmount  # noqa: F401,E501
from enzona_payment.models.operations_post_complete_items import OperationsPostCompleteItems  # noqa: F401,E501


class OperationsPostComplete(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'invoice_number': 'str',
        'merchant_op_id': 'str',
        'terminal_id': 'str',
        'amount': 'FullOperationsOperationAmount',
        'items': 'list[OperationsPostCompleteItems]'
    }

    attribute_map = {
        'description': 'description',
        'invoice_number': 'invoice_number',
        'merchant_op_id': 'merchant_op_id',
        'terminal_id': 'terminal_id',
        'amount': 'amount',
        'items': 'items'
    }

    def __init__(self, description=None, invoice_number=None, merchant_op_id=None, terminal_id=None, amount=None, items=None):  # noqa: E501
        """OperationsPostComplete - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._invoice_number = None
        self._merchant_op_id = None
        self._terminal_id = None
        self._amount = None
        self._items = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if invoice_number is not None:
            self.invoice_number = invoice_number
        if merchant_op_id is not None:
            self.merchant_op_id = merchant_op_id
        if terminal_id is not None:
            self.terminal_id = terminal_id
        if amount is not None:
            self.amount = amount
        if items is not None:
            self.items = items

    @property
    def description(self):
        """Gets the description of this OperationsPostComplete.  # noqa: E501


        :return: The description of this OperationsPostComplete.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OperationsPostComplete.


        :param description: The description of this OperationsPostComplete.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def invoice_number(self):
        """Gets the invoice_number of this OperationsPostComplete.  # noqa: E501


        :return: The invoice_number of this OperationsPostComplete.  # noqa: E501
        :rtype: str
        """
        return self._invoice_number

    @invoice_number.setter
    def invoice_number(self, invoice_number):
        """Sets the invoice_number of this OperationsPostComplete.


        :param invoice_number: The invoice_number of this OperationsPostComplete.  # noqa: E501
        :type: str
        """

        self._invoice_number = invoice_number

    @property
    def merchant_op_id(self):
        """Gets the merchant_op_id of this OperationsPostComplete.  # noqa: E501


        :return: The merchant_op_id of this OperationsPostComplete.  # noqa: E501
        :rtype: str
        """
        return self._merchant_op_id

    @merchant_op_id.setter
    def merchant_op_id(self, merchant_op_id):
        """Sets the merchant_op_id of this OperationsPostComplete.


        :param merchant_op_id: The merchant_op_id of this OperationsPostComplete.  # noqa: E501
        :type: str
        """

        self._merchant_op_id = merchant_op_id

    @property
    def terminal_id(self):
        """Gets the terminal_id of this OperationsPostComplete.  # noqa: E501


        :return: The terminal_id of this OperationsPostComplete.  # noqa: E501
        :rtype: str
        """
        return self._terminal_id

    @terminal_id.setter
    def terminal_id(self, terminal_id):
        """Sets the terminal_id of this OperationsPostComplete.


        :param terminal_id: The terminal_id of this OperationsPostComplete.  # noqa: E501
        :type: str
        """

        self._terminal_id = terminal_id

    @property
    def amount(self):
        """Gets the amount of this OperationsPostComplete.  # noqa: E501


        :return: The amount of this OperationsPostComplete.  # noqa: E501
        :rtype: FullOperationsOperationAmount
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this OperationsPostComplete.


        :param amount: The amount of this OperationsPostComplete.  # noqa: E501
        :type: FullOperationsOperationAmount
        """

        self._amount = amount

    @property
    def items(self):
        """Gets the items of this OperationsPostComplete.  # noqa: E501


        :return: The items of this OperationsPostComplete.  # noqa: E501
        :rtype: list[OperationsPostCompleteItems]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this OperationsPostComplete.


        :param items: The items of this OperationsPostComplete.  # noqa: E501
        :type: list[OperationsPostCompleteItems]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperationsPostComplete, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperationsPostComplete):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
