# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from enzona_payment.models.pagination_links import PaginationLinks  # noqa: F401,E501


class Pagination(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_page': 'int',
        'total_page': 'int',
        'page_size': 'int',
        'total': 'int',
        'links': 'PaginationLinks'
    }

    attribute_map = {
        'current_page': 'current_page',
        'total_page': 'total_page',
        'page_size': 'page_size',
        'total': 'total',
        'links': 'links'
    }

    def __init__(self, current_page=None, total_page=None, page_size=None, total=None, links=None):  # noqa: E501
        """Pagination - a model defined in Swagger"""  # noqa: E501

        self._current_page = None
        self._total_page = None
        self._page_size = None
        self._total = None
        self._links = None
        self.discriminator = None

        if current_page is not None:
            self.current_page = current_page
        if total_page is not None:
            self.total_page = total_page
        if page_size is not None:
            self.page_size = page_size
        if total is not None:
            self.total = total
        if links is not None:
            self.links = links

    @property
    def current_page(self):
        """Gets the current_page of this Pagination.  # noqa: E501


        :return: The current_page of this Pagination.  # noqa: E501
        :rtype: int
        """
        return self._current_page

    @current_page.setter
    def current_page(self, current_page):
        """Sets the current_page of this Pagination.


        :param current_page: The current_page of this Pagination.  # noqa: E501
        :type: int
        """

        self._current_page = current_page

    @property
    def total_page(self):
        """Gets the total_page of this Pagination.  # noqa: E501


        :return: The total_page of this Pagination.  # noqa: E501
        :rtype: int
        """
        return self._total_page

    @total_page.setter
    def total_page(self, total_page):
        """Sets the total_page of this Pagination.


        :param total_page: The total_page of this Pagination.  # noqa: E501
        :type: int
        """

        self._total_page = total_page

    @property
    def page_size(self):
        """Gets the page_size of this Pagination.  # noqa: E501


        :return: The page_size of this Pagination.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this Pagination.


        :param page_size: The page_size of this Pagination.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def total(self):
        """Gets the total of this Pagination.  # noqa: E501


        :return: The total of this Pagination.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this Pagination.


        :param total: The total of this Pagination.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def links(self):
        """Gets the links of this Pagination.  # noqa: E501


        :return: The links of this Pagination.  # noqa: E501
        :rtype: PaginationLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this Pagination.


        :param links: The links of this Pagination.  # noqa: E501
        :type: PaginationLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pagination, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pagination):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
