# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Payload3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_password': 'str',
        'funding_source_uuid': 'str'
    }

    attribute_map = {
        'payment_password': 'payment_password',
        'funding_source_uuid': 'funding_source_uuid'
    }

    def __init__(self, payment_password=None, funding_source_uuid=None):  # noqa: E501
        """Payload3 - a model defined in Swagger"""  # noqa: E501

        self._payment_password = None
        self._funding_source_uuid = None
        self.discriminator = None

        if payment_password is not None:
            self.payment_password = payment_password
        if funding_source_uuid is not None:
            self.funding_source_uuid = funding_source_uuid

    @property
    def payment_password(self):
        """Gets the payment_password of this Payload3.  # noqa: E501


        :return: The payment_password of this Payload3.  # noqa: E501
        :rtype: str
        """
        return self._payment_password

    @payment_password.setter
    def payment_password(self, payment_password):
        """Sets the payment_password of this Payload3.


        :param payment_password: The payment_password of this Payload3.  # noqa: E501
        :type: str
        """

        self._payment_password = payment_password

    @property
    def funding_source_uuid(self):
        """Gets the funding_source_uuid of this Payload3.  # noqa: E501


        :return: The funding_source_uuid of this Payload3.  # noqa: E501
        :rtype: str
        """
        return self._funding_source_uuid

    @funding_source_uuid.setter
    def funding_source_uuid(self, funding_source_uuid):
        """Sets the funding_source_uuid of this Payload3.


        :param funding_source_uuid: The funding_source_uuid of this Payload3.  # noqa: E501
        :type: str
        """

        self._funding_source_uuid = funding_source_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Payload3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Payload3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
