# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Payload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'currency': 'str',
        'amount': 'str',
        'merchant_op_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'currency': 'currency',
        'amount': 'amount',
        'merchant_op_id': 'merchant_op_id'
    }

    def __init__(self, description=None, currency=None, amount=None, merchant_op_id=None):  # noqa: E501
        """Payload - a model defined in Swagger"""  # noqa: E501

        self._description = None
        self._currency = None
        self._amount = None
        self._merchant_op_id = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if currency is not None:
            self.currency = currency
        if amount is not None:
            self.amount = amount
        if merchant_op_id is not None:
            self.merchant_op_id = merchant_op_id

    @property
    def description(self):
        """Gets the description of this Payload.  # noqa: E501


        :return: The description of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Payload.


        :param description: The description of this Payload.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def currency(self):
        """Gets the currency of this Payload.  # noqa: E501


        :return: The currency of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Payload.


        :param currency: The currency of this Payload.  # noqa: E501
        :type: str
        """
        allowed_values = ["CUP", "CUC"]  # noqa: E501
        if currency not in allowed_values:
            raise ValueError(
                "Invalid value for `currency` ({0}), must be one of {1}"  # noqa: E501
                .format(currency, allowed_values)
            )

        self._currency = currency

    @property
    def amount(self):
        """Gets the amount of this Payload.  # noqa: E501


        :return: The amount of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Payload.


        :param amount: The amount of this Payload.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def merchant_op_id(self):
        """Gets the merchant_op_id of this Payload.  # noqa: E501


        :return: The merchant_op_id of this Payload.  # noqa: E501
        :rtype: str
        """
        return self._merchant_op_id

    @merchant_op_id.setter
    def merchant_op_id(self, merchant_op_id):
        """Sets the merchant_op_id of this Payload.


        :param merchant_op_id: The merchant_op_id of this Payload.  # noqa: E501
        :type: str
        """
        # allowed_values = ["123456789123"]  # noqa: E501
        # if merchant_op_id not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `merchant_op_id` ({0}), must be one of {1}"  # noqa: E501
        #         .format(merchant_op_id, allowed_values)
        #     )

        self._merchant_op_id = merchant_op_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Payload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Payload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
