# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PaymentsstoreItems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vendor_identity_code': 'str',
        'product_id': 'str',
        'quantity': 'int',
        'price': 'float'
    }

    attribute_map = {
        'vendor_identity_code': 'vendor_identity_code',
        'product_id': 'product_id',
        'quantity': 'quantity',
        'price': 'price'
    }

    def __init__(self, vendor_identity_code=None, product_id=None, quantity=None, price=None):  # noqa: E501
        """PaymentsstoreItems - a model defined in Swagger"""  # noqa: E501

        self._vendor_identity_code = None
        self._product_id = None
        self._quantity = None
        self._price = None
        self.discriminator = None

        if vendor_identity_code is not None:
            self.vendor_identity_code = vendor_identity_code
        if product_id is not None:
            self.product_id = product_id
        if quantity is not None:
            self.quantity = quantity
        if price is not None:
            self.price = price

    @property
    def vendor_identity_code(self):
        """Gets the vendor_identity_code of this PaymentsstoreItems.  # noqa: E501


        :return: The vendor_identity_code of this PaymentsstoreItems.  # noqa: E501
        :rtype: str
        """
        return self._vendor_identity_code

    @vendor_identity_code.setter
    def vendor_identity_code(self, vendor_identity_code):
        """Sets the vendor_identity_code of this PaymentsstoreItems.


        :param vendor_identity_code: The vendor_identity_code of this PaymentsstoreItems.  # noqa: E501
        :type: str
        """

        self._vendor_identity_code = vendor_identity_code

    @property
    def product_id(self):
        """Gets the product_id of this PaymentsstoreItems.  # noqa: E501


        :return: The product_id of this PaymentsstoreItems.  # noqa: E501
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this PaymentsstoreItems.


        :param product_id: The product_id of this PaymentsstoreItems.  # noqa: E501
        :type: str
        """

        self._product_id = product_id

    @property
    def quantity(self):
        """Gets the quantity of this PaymentsstoreItems.  # noqa: E501


        :return: The quantity of this PaymentsstoreItems.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this PaymentsstoreItems.


        :param quantity: The quantity of this PaymentsstoreItems.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this PaymentsstoreItems.  # noqa: E501


        :return: The price of this PaymentsstoreItems.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PaymentsstoreItems.


        :param price: The price of this PaymentsstoreItems.  # noqa: E501
        :type: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentsstoreItems, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentsstoreItems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
