# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PaymentFullInfoPayerPayerInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'payer_id': 'str'
    }

    attribute_map = {
        'username': 'username',
        'first_name': 'first_name',
        'last_name': 'last_name',
        'payer_id': 'payer_id'
    }

    def __init__(self, username=None, first_name=None, last_name=None, payer_id=None):  # noqa: E501
        """PaymentFullInfoPayerPayerInfo - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._first_name = None
        self._last_name = None
        self._payer_id = None
        self.discriminator = None

        if username is not None:
            self.username = username
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if payer_id is not None:
            self.payer_id = payer_id

    @property
    def username(self):
        """Gets the username of this PaymentFullInfoPayerPayerInfo.  # noqa: E501


        :return: The username of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this PaymentFullInfoPayerPayerInfo.


        :param username: The username of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def first_name(self):
        """Gets the first_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501


        :return: The first_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this PaymentFullInfoPayerPayerInfo.


        :param first_name: The first_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501


        :return: The last_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this PaymentFullInfoPayerPayerInfo.


        :param last_name: The last_name of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def payer_id(self):
        """Gets the payer_id of this PaymentFullInfoPayerPayerInfo.  # noqa: E501


        :return: The payer_id of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :rtype: str
        """
        return self._payer_id

    @payer_id.setter
    def payer_id(self, payer_id):
        """Sets the payer_id of this PaymentFullInfoPayerPayerInfo.


        :param payer_id: The payer_id of this PaymentFullInfoPayerPayerInfo.  # noqa: E501
        :type: str
        """

        self._payer_id = payer_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentFullInfoPayerPayerInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentFullInfoPayerPayerInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
