# coding: utf-8

"""
    PaymentAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from enzona_payment.models.payment_full_info_payer_payer_info import PaymentFullInfoPayerPayerInfo  # noqa: F401,E501


class PaymentFullInfoPayer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payer_info': 'PaymentFullInfoPayerPayerInfo'
    }

    attribute_map = {
        'payer_info': 'payer_info'
    }

    def __init__(self, payer_info=None):  # noqa: E501
        """PaymentFullInfoPayer - a model defined in Swagger"""  # noqa: E501

        self._payer_info = None
        self.discriminator = None

        if payer_info is not None:
            self.payer_info = payer_info

    @property
    def payer_info(self):
        """Gets the payer_info of this PaymentFullInfoPayer.  # noqa: E501


        :return: The payer_info of this PaymentFullInfoPayer.  # noqa: E501
        :rtype: PaymentFullInfoPayerPayerInfo
        """
        return self._payer_info

    @payer_info.setter
    def payer_info(self, payer_info):
        """Sets the payer_info of this PaymentFullInfoPayer.


        :param payer_info: The payer_info of this PaymentFullInfoPayer.  # noqa: E501
        :type: PaymentFullInfoPayerPayerInfo
        """

        self._payer_info = payer_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentFullInfoPayer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentFullInfoPayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
